Functions for tables and displays
bootstrapworld/curriculum pull request #1229
Opened 2022-12-14 22:38 UTC by flannery-denny

My sense is this a good start that we can live with... and it will probably evolve :) 

- Totally open to it doing more lifting if you have other ideas. 
- I expect fresh eyes will lead to a few more synthesize questions.
- I'm uncertain about the formatting for the first Investigate section - feel free to adjust if you have other ideas about how to make it more readable.

2022-12-16 16:31 UTC, schanzer requested changes
@flannery-denny this looks great! I think Circles definitely don't fit here. :) 

My one major question is about Contracts mostly showing up in workbook pages and not the lesson itself. I'd love to see this show up more in the lesson plan itself, so it's clear to teachers how significant this is. Maybe even retitle the first section "Contracts and Tables" to drive home the point??

2022-12-16 16:31 UTC, schanzer commented on lessons/table-and-display-functions/langs/en-us/pages/exploring-displays-alt.adoc
> += Exploring Displays
I would swap the columns in each subtable, so that the _first_ thing kids do is draw a pretty picture.

2023-01-02 22:20 UTC, flannery-denny commented
@schanzer I think this is ready to merge.

2023-01-02 22:20 UTC, flannery-denny commented on lessons/table-and-display-functions/langs/en-us/pages/functions-for-tables.adoc
> +Contracts can also be written with more detail, by describing data types in the Domain:
leaving this as is per our conversation.

2023-01-02 22:21 UTC, flannery-denny commented on lessons/table-and-display-functions/langs/en-us/pages/functions-for-tables.adoc
> +- Each contract begins with the function name: @fitb{10em}{_in this case_ `sort`}
leaving this as is per our conversation

2023-01-02 22:22 UTC, flannery-denny commented on lessons/table-and-display-functions/langs/en-us/pages/functions-for-tables.adoc
> +There are many many functions available to us in Pyret. We can describe them using contracts. The contract for `sort` is:
not 100% sure whether you are still looking for a change here.

2023-01-03 20:11 UTC, merged