New early math lesson
bootstrapworld/curriculum pull request #1292
Opened 2023-03-09 20:58 UTC by retabak

entered the world of.... fractions !

2023-03-09 22:11 UTC, schanzer requested changes
This looks _really_ awesome. I think you'll likely learn a lot by testing it out in the 1-day PD, so I'm mostly recommending small changes. The one major issue is the workbook page that I called out -- happy to chat about it by phone if you want.

2023-03-09 22:11 UTC, schanzer commented on lessons/Early-Math/inverse-relationships/langs/en-us/pages/divide-first-or-left-to-right.adoc
> += Divide First... or Solve Left-to-Right?
This is _excellent_. Really nicely done!

I fixed a small formatting issue

2023-03-09 22:18 UTC, retabak commented on lessons/Early-Math/inverse-relationships/langs/en-us/pages/discover-inverse.adoc
> +@n Examine the Circles of Evaluation below.
omg, let's please discuss. I have no idea how to fix it! I totally leaned hard on "examine" when "analyze" was firmly rejected by you and Flannery.

2023-03-10 00:30 UTC, retabak commented on lessons/Early-Math/inverse-relationships/langs/en-us/pages/discover-inverse.adoc
> +How is this pair of Circles similar to the first pair on this page? How is it different? @fitb{}{@ifsoln{The same values are being used, but this time we are dividing by the fraction,}}
funny, I originally had something else then decided it should be the same to help students see the difference. But I guess it didn't have that effect?

2023-03-10 00:31 UTC, retabak commented on lessons/Early-Math/inverse-relationships/langs/en-us/pages/discover-inverse.adoc
> +Below, draw another pair of Circles tp demonstrates how _dividing by a whole number_ produces the same result as _multiplying by its reciprocal._
good call.

2023-03-23 14:51 UTC, closed without merging