Codap display lessons
bootstrapworld/curriculum pull request #1651
Opened 2023-11-17 17:14 UTC by retabak

There are a gazillion tiny little changes here to slides, workbook pages, and lessons, usually using @ifproglang{}{}. 

I still need to create data cycle answer keys but then I *think* this is ready!

2023-11-17 17:16 UTC, schanzer commented
@retabak happy to review this tonight, but I think you should finish the solutions before we merge this. You can still keep pushing to the branch, and the committable shop as part of this PR.

2023-11-17 17:24 UTC, retabak commented
sounds good! I'll try to do that today.

2023-11-17 19:14 UTC, retabak commented
done!

2023-11-20 20:17 UTC, schanzer requested changes
@retabak sorry for the delay on this review!

I worked through all of the lessons up to grouped samples, but after that I only skimmed. My biggest meta-comment is really a question: do you think these lessons need some extra codap-specific instruction reminding students where to find the buttons/options for each display? Or do you think they're straightforward enough that kids will remembr after doing the initial codap-exploring lesson?

Please also see my note about prerequisites that still need to have a codap version.

Finally -- we need a codap-specific version of the exploration paper template. The one linked from all of these lessons is Pyret-specific.

2023-11-20 20:31 UTC, retabak commented on lessons/Data-Science/bar-and-pie-charts/langs/en-us/pages/infographic.adoc
> +- Option 1: Build bar or pie charts in @ifproglang{pyret}{Pyret from @starter-file{food}}@ifproglang{codap}{@link{https://docs.google.com/spreadsheets/d/1DYVHT7SSjnoDp4MQ80Z1qZSqFdEIlR8Gd20eMx9f1JA/e
I have literally no idea why I did this. I suspect I did a "find in files" for "projects" and was on autopilot. Woops.

2023-11-20 20:31 UTC, retabak commented on lessons/Data-Science/bar-and-pie-charts/langs/en-us/pages/infographic.adoc
> +- Option 1: Build bar or pie charts in @ifproglang{pyret}{Pyret from @starter-file{food}}@ifproglang{codap}{@link{https://docs.google.com/spreadsheets/d/1DYVHT7SSjnoDp4MQ80Z1qZSqFdEIlR8Gd20eMx9f1JA/e
for what it's worth, I did add the NEW infogrpahic project-lesson to the codap pathway.

2023-11-20 20:34 UTC, retabak commented on lessons/Data-Science/histograms/langs/en-us/index.adoc
wondering if data-displays-organizer (from codap-dot-plots-bar-charts) would be an adequate stand-in for the contracts page?

<img width="640" alt="image" src="https://github.com/bootstrapworld/curriculum/assets/87144723/fe5374c4-cfdf-4a9d-ad27-1e1e6fa42756">

2023-11-20 20:37 UTC, retabak commented on lessons/Data-Science/measures-of-center/langs/en-us/slides.md
> +@ifproglang{pyret}{Pyret}@ifproglang{codap}{CODAP} has a way for us to compute the mean of any @vocab{quantitative} column in a Table. It consumes a Table and the name of the column you want to measu
Kids don't need to go to the transformers menu here, and have not yet been introduced to transformers (so that would be an unreasonable ask!).

2023-11-20 20:38 UTC, retabak commented on lessons/Data-Science/standard-deviation/langs/en-us/index.adoc
I had that same thought then got lazy. I'll fix!

2023-11-29 17:36 UTC, retabak commented on lessons/Data-Science/measures-of-center/langs/en-us/slides.md
> +@ifproglang{pyret}{Pyret}@ifproglang{codap}{CODAP} has a way for us to compute the mean of any @vocab{quantitative} column in a Table. It consumes a Table and the name of the column you want to measu
@schanzer - is this confusing? Your comment doesn't quite make sense here. Will leave as is unless you clarify further.

2023-11-30 13:11 UTC, schanzer approved these changes
@retabak I think you've addressed all of my concerns here! I suspect you'll find a lot more papercuts once you run PD on these new lessons, but they're in good enough shape to merge!

2023-11-30 20:14 UTC, merged