Commutative w code
bootstrapworld/curriculum pull request #1691
Opened 2023-12-11 15:11 UTC by retabak

sorry, forgot to push some things on the last PR. Here's a new one!

2023-12-12 16:04 UTC, schanzer requested changes
Overall looking good. One item to change, which we should discuss in our meeting

2023-12-13 01:13 UTC, retabak commented
@schanzer - I believe that I've responded to your feedback. Take a look and let me know if this looks ready to merge!

2023-12-13 02:04 UTC, schanzer requested changes
Don't kill me -- I liked your justification when you explained it, but after reading the code section again I am even more convinced it doesn't hang together. I left you some very concrete feedback, which I hope (a) makes sense and (b) is helpful.

2023-12-13 02:04 UTC, schanzer commented on lessons/Early-Math/commutative-property/langs/en-us/index.adoc
> +In the last activity, we discovered that _none_ of the image-producing functions on the page were commutative! Do you think there are any functions in @proglang that are commutative? Let's answer tha
You're asking them to answer a simple yes-or-no question, when thinking about the actual answer would be nearly impossible without having more examples of image-producing functions. That means students will just flip a coin and pick "yes" or "no", neither of which is helping them think through stuff.

I'm sorry to disappoint you, but now I'm even more convinced that this section is backwards. Here's how I would set it up:

- Give kids a workbook page with `above`, `beside`, and `overlay`. For each one, have them read the contract, convert a given COE to code, then draw the COE with arguments swapped. Students have to make a prediction about whether they will get the same value back by _drawing the image they predict they'll get back_ when they convert the swapped COE to code. Have them try it out, draw the answer, then circle "commutative" or "not commutative".  At the bottom, leave an open response that asks them if they can imagine an image function that IS commutative
- Page 2: Same formula, but with`string-contains`, `min`, `max`, and `blend-images`

2023-12-13 02:04 UTC, schanzer commented on lessons/Early-Math/commutative-property/langs/en-us/pages/commutativity-and-code2.adoc
> +@n Use @proglang to test your prediction. What did you discover? @fitb{}{@ifsoln{`max` is commutative.}}
I also think that asking them to do so much writing is overkill, especially given that our audience is younger and this is literally a yes/no answer anyway

2023-12-13 02:06 UTC, retabak commented on lessons/Early-Math/commutative-property/langs/en-us/index.adoc
> +Think about the function `beside`, which takes in two images - let's say a green star and a blue square - and places them one next to the other.
They do! The Contacts lesson is in early math.

2023-12-13 02:07 UTC, schanzer commented on lessons/Early-Math/commutative-property/langs/en-us/index.adoc
> +Think about the function `beside`, which takes in two images - let's say a green star and a blue square - and places them one next to the other.
That lesson does not cover `beside`. In fact, it doesn't cover any of the image functions you use here.

Open the lesson plan and do a search for "beside".

2023-12-14 16:45 UTC, closed without merging